// Scholar difficulty. Convention: the first option in each array is always correct.
export const hard = {
  "Which organelle is responsible for ATP synthesis via oxidative phosphorylation?": ["Mitochondria", "Chloroplast", "Ribosome", "Lysosome"],
  "Who formulated the laws of planetary motion?": ["Johannes Kepler", "Isaac Newton", "Galileo Galilei", "Nicolaus Copernicus"],
  "What is the term for a group of lions?": ["A pride", "A pack", "A herd", "A flock"],
  "Which element has the atomic number 1?": ["Hydrogen", "Helium", "Lithium", "Oxygen"],
  "Which philosophical work contains the phrase \"Cogito, ergo sum\"?": ["Discourse on the Method", "The Republic", "Critique of Pure Reason", "Leviathan"],
  "What is the SI unit of electric resistance?": ["Ohm", "Volt", "Ampere", "Watt"],
  "Who wrote \"One Hundred Years of Solitude\"?": ["Gabriel García Márquez", "Pablo Neruda", "Jorge Luis Borges", "Mario Vargas Llosa"],
  "What is the smallest unit of an element that retains its chemical properties?": ["Atom", "Molecule", "Ion", "Electron"],
  "Which empire was ruled by Genghis Khan?": ["Mongol Empire", "Ottoman Empire", "Roman Empire", "Persian Empire"],
  "What is the derivative of sin(x)?": ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"],
  "Which treaty officially ended World War I?": ["Treaty of Versailles", "Treaty of Paris", "Treaty of Tordesillas", "Treaty of Westphalia"],
  "What is a triangle with no equal sides called?": ["Scalene", "Isosceles", "Equilateral", "Right"],
  "Which scientist proposed the theory of natural selection?": ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Alfred Wallace"],
  "Sucrose is composed of which two simple sugars?": ["Glucose and fructose", "Glucose and galactose", "Two glucose molecules", "Fructose and galactose"],
  "In which year did the Berlin Wall fall?": ["1989", "1991", "1979", "1985"],
  "According to the Pythagorean identity, sin²(x) + cos²(x) equals what?": ["1", "0", "-1", "2"],
  "Who wrote \"The Wealth of Nations,\" a foundational text of modern economics?": ["Adam Smith", "John Maynard Keynes", "Karl Marx", "David Ricardo"],
  "What is the process by which water vapor turns into liquid called?": ["Condensation", "Evaporation", "Sublimation", "Precipitation"],
  "Which gas is most responsible for the greenhouse effect on Earth?": ["Carbon dioxide", "Oxygen", "Nitrogen", "Argon"],
  "What was the capital of the Byzantine Empire?": ["Constantinople", "Athens", "Rome", "Alexandria"],
  "Who composed the Ninth Symphony, which features the \"Ode to Joy\"?": ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert"],
  "What is the integral of 1/x with respect to x?": ["ln|x| + C", "x²/2 + C", "1/x² + C", "eˣ + C"],
  "Which country was the first to grant women the right to vote nationally?": ["New Zealand", "United States", "United Kingdom", "France"],
  "What is an organism that produces its own food through photosynthesis called?": ["Autotroph", "Heterotroph", "Decomposer", "Saprotroph"],
  "Which 1215 document limited the power of the English monarchy?": ["Magna Carta", "Bill of Rights", "Treaty of Versailles", "Declaration of Independence"],
  "Who developed the periodic table of elements?": ["Dmitri Mendeleev", "Marie Curie", "Antoine Lavoisier", "Niels Bohr"],
  "What is a polygon with eight sides called?": ["Octagon", "Hexagon", "Heptagon", "Nonagon"],
  "Which ancient civilization built the pyramids of Giza?": ["Egyptians", "Mayans", "Greeks", "Romans"],
  "Which physical law states that energy cannot be created or destroyed?": ["Conservation of energy", "Conservation of mass", "Newton's third law", "Law of inertia"],
  "Who wrote the play \"Hamlet\"?": ["William Shakespeare", "Christopher Marlowe", "Ben Jonson", "Oscar Wilde"],
  "What is the value of the mathematical constant e, rounded to two decimal places?": ["2.72", "3.14", "1.41", "1.62"],
  "Which scientist discovered penicillin?": ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Joseph Lister"],
  "What branch of mathematics deals with rates of change and accumulation?": ["Calculus", "Algebra", "Geometry", "Statistics"],
  "Which modern country was formerly known as Persia?": ["Iran", "Iraq", "Turkey", "Syria"],
  "What is the legal principle that a person is innocent until proven guilty called?": ["Presumption of innocence", "Due process", "Habeas corpus", "Double jeopardy"],
  "Who painted \"The Starry Night\"?": ["Vincent van Gogh", "Claude Monet", "Salvador Dalí", "Henri Matisse"],
  "What is the SI unit of frequency?": ["Hertz", "Watt", "Joule", "Pascal"],
  "What is a gradual shift in the meaning of a word over time called?": ["Semantic change", "Phonetic shift", "Syntax drift", "Morphological shift"],
  "Which river flows through Egypt?": ["The Nile", "The Amazon", "The Tigris", "The Euphrates"],
  "The equation a² + b² = c² for right triangles is known as what?": ["The Pythagorean theorem", "Fermat's last theorem", "Euclid's theorem", "The law of cosines"],
  "Who was the first emperor of Rome?": ["Augustus", "Julius Caesar", "Nero", "Constantine"],
  "What is the process by which cells divide to form gametes called?": ["Meiosis", "Mitosis", "Cytokinesis", "Fertilization"],
  "What is the chemical symbol for sodium?": ["Na", "So", "Sd", "S"],
  "Which philosopher wrote \"The Republic\"?": ["Plato", "Aristotle", "Socrates", "Confucius"],
  "Which event is considered the start of the French Revolution?": ["Storming of the Bastille", "Fall of the Berlin Wall", "Boston Tea Party", "Signing of the Magna Carta"],
  "What is an angle greater than 90 but less than 180 degrees called?": ["Obtuse angle", "Acute angle", "Right angle", "Reflex angle"],
  "Who developed the theory of general relativity?": ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"],
  "What is cellular respiration that occurs without oxygen called?": ["Anaerobic respiration", "Aerobic respiration", "Photosynthesis", "Osmosis"],
  "Which language has the most native speakers worldwide?": ["Mandarin Chinese", "English", "Spanish", "Hindi"],
  "What is a government ruled by a single absolute ruler called?": ["Autocracy", "Democracy", "Oligarchy", "Republic"],
};

export default hard;