// 8th Grader difficulty. Convention: the first option in each array is always correct.
export const med = {
  "What is the chemical symbol for water?": ["H2O", "CO2", "O2", "NaCl"],
  "What planet is known as the Red Planet?": ["Mars", "Venus", "Jupiter", "Saturn"],
  "What is the powerhouse of the cell?": ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"],
  "What is the capital of France?": ["Paris", "Berlin", "Madrid", "Rome"],
  "What is the capital of Japan?": ["Tokyo", "Beijing", "Seoul", "Bangkok"],
  "Who wrote \"Romeo and Juliet\"?": ["William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"],
  "What is the largest ocean on Earth?": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
  "What is the square root of 64?": ["8", "6", "9", "7"],
  "How many continents are there?": ["7", "5", "6", "8"],
  "What gas do plants absorb from the atmosphere?": ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
  "What is the freezing point of water in Celsius?": ["0", "32", "100", "-10"],
  "What is the boiling point of water in Celsius?": ["100", "0", "212", "50"],
  "Who was the first President of the United States?": ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"],
  "What is the longest river in the world?": ["Nile River", "Amazon River", "Yangtze River", "Mississippi River"],
  "What is the smallest prime number?": ["2", "1", "3", "0"],
  "What organ pumps blood throughout the body?": ["Heart", "Liver", "Lungs", "Kidney"],
  "What is the approximate speed of light?": ["300,000 km/s", "150,000 km/s", "1,000 km/s", "3,000 km/s"],
  "What does \"DNA\" stand for?": ["Deoxyribonucleic acid", "Dioxyribonucleic acid", "Deoxyribose nuclear acid", "Dinitrogen acid"],
  "Which planet is closest to the sun?": ["Mercury", "Venus", "Earth", "Mars"],
  "What is the main language spoken in Brazil?": ["Portuguese", "Spanish", "French", "Italian"],
  "What is the hardest natural substance on Earth?": ["Diamond", "Gold", "Iron", "Quartz"],
  "Who painted the Mona Lisa?": ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
  "What is the chemical symbol for gold?": ["Au", "Ag", "Gd", "Go"],
  "Which organelle is responsible for making proteins?": ["Ribosome", "Mitochondria", "Nucleus", "Vacuole"],
  "What is 12 x 12?": ["144", "132", "124", "156"],
  "What is the value of pi, rounded to two decimal places?": ["3.14", "3.41", "1.34", "4.13"],
  "Which gas makes up most of Earth's atmosphere?": ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"],
  "What is the largest planet in our solar system?": ["Jupiter", "Saturn", "Neptune", "Earth"],
  "In which country would you find the Great Wall?": ["China", "Japan", "India", "Mongolia"],
  "What is the basic unit of life?": ["Cell", "Atom", "Tissue", "Organ"],
  "What is the currency used in the United Kingdom?": ["Pound", "Euro", "Dollar", "Franc"],
  "How many sides does a hexagon have?": ["6", "5", "7", "8"],
  "What is the process by which plants make food called?": ["Photosynthesis", "Respiration", "Digestion", "Fermentation"],
  "Who developed the theory of relativity?": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"],
  "What is the tallest mountain in the world?": ["Mount Everest", "K2", "Kilimanjaro", "Denali"],
  "What does \"WWW\" stand for?": ["World Wide Web", "World Wide Wire", "Wide World Web", "World Web Wide"],
  "What is the main ingredient in bread?": ["Flour", "Sugar", "Butter", "Salt"],
  "What number is a dozen?": ["12", "10", "20", "6"],
  "Which country is known as the Land of the Rising Sun?": ["Japan", "China", "Thailand", "South Korea"],
  "What part of the plant absorbs water from the soil?": ["Roots", "Leaves", "Stem", "Flower"],
  "What is the study of living organisms called?": ["Biology", "Geology", "Chemistry", "Physics"],
  "In which year did World War II end?": ["1945", "1939", "1918", "1950"],
  "What shape has 5 sides?": ["Pentagon", "Hexagon", "Octagon", "Square"],
  "What is the chemical formula for table salt?": ["NaCl", "KCl", "CaCl2", "NaOH"],
  "What is the largest mammal in the world?": ["Blue whale", "Elephant", "Giraffe", "Hippopotamus"],
  "What instrument measures temperature?": ["Thermometer", "Barometer", "Hygrometer", "Anemometer"],
  "What is the capital city of Australia?": ["Canberra", "Sydney", "Melbourne", "Perth"],
  "What do you call a triangle with all sides equal?": ["Equilateral", "Isosceles", "Scalene", "Right"],
  "What is the main gas found in the sun?": ["Hydrogen", "Helium", "Oxygen", "Nitrogen"],
  "How many bones are in the adult human body?": ["206", "300", "150", "250"],
};

export default med;